from autogen import AssistantAgent, UserProxyAgent
from autogen import ConversableAgent
from autogen import GroupChatManager
from autogen import GroupChat
from autogen import register_function
from autogen.agentchat.contrib.retrieve_user_proxy_agent import RetrieveUserProxyAgent

from skillsControl import *
from autogen.coding import LocalCommandLineCodeExecutor
from dotenv import load_dotenv
from autogen import ConversableAgent
import os
import tempfile
# from autogen.agentchat.contrib.capabilities import transform_messages
# from autogen.agentchat.contrib.capabilities.text_compressors import LLMLingua
# from autogen.agentchat.contrib.capabilities.transforms import TextMessageCompressor

load_dotenv()
#, "base_url": os.environ.get("OPENAI_API_BASE")
config_list = {"config_list": [{"model": "gpt-4o", "api_key": os.environ.get("OPENAI_API_KEY"), "timeout": 100, "cache_seed": None}]}

temp_dir = tempfile.TemporaryDirectory()

# 代码执行器
executor = LocalCommandLineCodeExecutor(
    timeout=10,  # Timeout for each code execution in seconds.
    work_dir=temp_dir.name,  # Use the temporary directory to store the code files.
)

# 代码执行代理 负责调用代码执行器来执行代理
Operator = ConversableAgent(
    name='Operator',
    llm_config=False,  # Turn off LLM for this agent.
    code_execution_config={"executor": executor},
    description='An operator is responsible for executing the code of agent skills and interacting with external data sources.Can only be called by Observable_engineer_agent!',
)

# 用户代理 发布任务，介入人机交互
User_proxy = UserProxyAgent(
    name='User_proxy_agent',
    code_execution_config=False
)
# 总运维工程师
Operation_Engineer_Agent = ConversableAgent(
    name='OperationEngineer',
    llm_config= config_list,
    human_input_mode="ALWAYS",
    system_message="""
                    #OBJECTIVE#
                    You are responsible for recording the analysis results generated by each participating expert, summarizing the analysis of all experts, and generating a root cause identification report.
                    #############
                    #CONTEXT#
                    Provide a template for the root cause identification report and a strategy for collating expert analysis using the Chain of Thought (COT) method. 
                    Analyze each expert's opinion step by step, explaining how each supports or supplements others. 
                    For conflicting conclusions, cross-validate with data, and if unresolved, request human intervention. 
                    Before summarizing, reflect on whether all expert analyses are fully verified. 
                    Finally, ask the human agent to confirm the root cause.
                    #############
                    #RESPONSE#
                    You need to respond with a root cause analysis report for the current incident, which should include the incident number, the roles of the experts involved, the expert analysis summary, and the final root cause.
                    #############
                    #SKILLS#
                    None        
                    """,
    description="Operation Engineer, responsible for referring to other experts' analysis and determining the root cause."
)
# 架构程序员
Architect_Expert_Agent = ConversableAgent(
    name='ArchitectExpert',
    llm_config=config_list,
    human_input_mode = "ALWAYS",
    system_message="""
                    #OBJECTIVE#
                    You need to provide cloud system architecture information such as dependencies and pod information in the trainticket microservice system.
                    #############
                    #CONTEXT#
                    In the current environment, you should provide the dependency information of the trainticket microservice system in text form here: based on the Kubernetes cluster, there is a trainticket microservice system, using the open source function computing framework OpenFaaS, and the main dependencies include: Java, OkHttp, Spring Boot development framework, MongoDB and its JDBC driver database, Docker container environment, and container IP information, pod related information
                    #############
                    #RESPONSE#
                    Your response must include cloud system service dependencies related to the current incident.
                    #############
                    #SKILLS#
                    Information reading skills: Ability to call cloud platform information and read pod, container quantity address and other information in local files.
                    """,
    description="Architecture Expert, provides system architecture related knowledge for other participants to analyze."
)

# 系统底层专家
Resource_Expert_Agent = ConversableAgent(
    name='ResourceExpert',
    llm_config=config_list,
    human_input_mode = "ALWAYS",
    system_message="""
                    #OBJECTIVE#
                    You are a Resource Agent. You need to analyze the cloud failure events in the current system based on your rich experience and database knowledge.
                    #############
                    #CONTEXT#
                    You need to first use your own search skills to obtain relevant historical cases and knowledge from the knowledge base. If similar events or experiences are retrieved, you should try to use them; if not, you need to rely on your own experience to make judgments.
                    Next, please make sure to perform the following steps:
                    1. You need to observe the current cloud event situation and analyze whether the problem is related to your professional field based on your current knowledge and judgment ability.
                    2. If it is determined that the event is related to your professional field, enter the hypothesis generation and verification cycle:
                       - Generate a hypothesis based on the observed information and your own knowledge.
                       - Determine whether the hypothesis has sufficient data support. You can use your skill to query the Observation Agent.
                       - If the hypothesis has sufficient data support, form a final conclusion and exit the loop.
                       - Otherwise, continue to generate new hypotheses and repeat the verification process.
                    3. If it is determined that the event is not related to your professional field, end the entire analysis process.
                    4. Return your final conclusion.
                    #############
                    #RESPONSE#
                    You should provide analysis results related to the system troubleshooting area in the current system failure event.
                    #############
                    #SKILLS#
                    You have the RAG knowledge base tool RAG(), which can retrieve similar historical events and knowledge experiences through similarity retrieval. You can call the function RAG() to obtain this capability.
                    """,
    description="Resource expert,provide system resource error analysis for Operation Engineers to analyze."
)

# 网络专家
NetWork_Expert_Agent = ConversableAgent(
    name='NetWorkExpert',
    llm_config=config_list,
    human_input_mode = "ALWAYS",
    system_message="""
                    #OBJECTIVE#
                    You are a Network Agent. 
                    You need to analyze the network and communication aspects of cloud failure events in the current system based on your rich experience and database knowledge.
                    #############
                    #CONTEXT#
                    You need to first use your own search skills to obtain relevant historical cases and knowledge from the knowledge base. 
                    If similar events or experiences are retrieved, you should try to use them; 
                    if not, you need to rely on your own experience to make judgments.
                    Next, please make sure to perform the following steps:
                    1. You need to observe the current cloud event situation and analyze whether the problem is related to your professional field based on your current knowledge and judgment ability.
                    2. If it is determined that the event is related to your professional field, enter the hypothesis generation and verification cycle:
                       - Generate a hypothesis based on the observed information and your own knowledge.
                       - Determine whether the hypothesis has sufficient data support. You can use your skill to query the Observation Agent.
                       - If the hypothesis has sufficient data support, form a final conclusion and exit the loop.
                       - Otherwise, continue to generate new hypotheses and repeat the verification process.
                    3. If it is determined that the event is not related to your professional field, end the entire analysis process.
                    4. Return your final conclusion.
                    #############
                    #RESPONSE#
                    You should provide analysis results related to the network and communication fields in the current system failure incident.
                    #############
                    #SKILLS#
                    You have the RAG knowledge base tool RAG(), which can retrieve similar historical events and knowledge experiences through similarity retrieval. You can call the function RAG() to obtain this capability.
                    """,
    description='Network expert, provide network fault analysis for Operation Engineers to analyze.'
)

# 数据观测人员 负责获取当前相关数据
Observable_engineer_agent = ConversableAgent(
    name='Observable_engineer_agent',
    llm_config=config_list,
    system_message="""
                    #OBJECTIVE#
                    You are an Observation Agent. 
                    Your responsibility is to observe the data of the TrainTickect microservice system and sort out the data related to the current exception.
                    #############
                    #CONTEXT#
                    - Environmental status: As a data observation agent, you must process abnormal data to ensure integrity and accuracy, then provide it to Operation Agent, System Agent and Network Agent for root cause analysis. 
                    You also handle event alarms, data queries, and request Human Agent intervention for content confirmation when generating data tickets.
                    - Data source types include metric, log, and trace, determined by the service platform's dataset. These types are correlated, so attention to foreign key associations is needed during extraction and processing.
                       - Metrics quantify system performance and behavior, stored in time series, and may include CPU, network, Pod, Node performance, etc., depending on the system.
                       - Logs are text records of system/application events, errors, and debugging, with fields like time, descriptions, and containers, based on the system's output.
                       - Trace files track a request's flow across services in distributed systems.
                    #############
                    #RESPONSE#
                    What you need to respond to is the abnormal data entries and corresponding abnormal fields filtered out from these three files, forming a data work order
                    #############
                    #SKILLS#
                    - Data query: You need to query timestamps and related service data via the data observation platform based on event alerts or expert requests.
                    - Data processing: Ensure data integrity and accuracy during processing.
                      - Metric data: During cloud failures, analyze historical metrics, retain data items within the event timeframe, and remove irrelevant metrics.
                      - Log data: Quickly extract logs related to the failure within a specific period, and filter further by service type or other conditions.
                      - Trajectory data: Extract data matching the failure timestamp, remove unrelated records, and simplify timestamps for consistency.
                    """,
    description='Observable engineer, Obtain current abnormal data and display it for analysis by operation and maintenance personnel.',
)

# RAG,可使用私有历史数据测试
RAG_user_proxy_agent = RetrieveUserProxyAgent(
    name="RAG_Assistant",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=3,
    retrieve_config={
        "task": "code",
        "docs_path": [
            "private/CMCC_fault_rag"
        ],
        "vector_db": "pgvector",
        "collection_name": "autogen_docs",
        "db_config": {
            "connection_string": "postgresql://test:abcd1234@localhost:5432/vectordb",
        },
        "custom_text_types": ["mdx"],
        "chunk_token_size": 2000,
        "model": "text-embedding-3-small",
        "get_or_create": True,
    },
    code_execution_config=False,
)

# Observable_engineer_agent's skills
# 获取数据的能力
register_function(
    alldata,
    caller=Observable_engineer_agent,  # The assistant agent can suggest calls to the calculator.
    executor=Operator,  # The user proxy agent can execute the calculator calls.
    name="data",  # By default, the function name is used as the tool name.
    description="A useful related data tool",  # A description of the tool.
)
# 获取架构信息能力
register_function(
    architectureData,
    caller=Observable_engineer_agent,  # The assistant agent can suggest calls to the calculator.
    executor=Operator,  # The user proxy agent can execute the calculator calls.
    name="architecture information",  # By default, the function name is used as the tool name.
    description="A useful tool for obtaining architecture information",  # A description of the tool.
)

# 处理数据能力
register_function(
    process_log_data,
    caller=Observable_engineer_agent,  # The assistant agent can suggest calls to the calculator.
    executor=Operator,  # The user proxy agent can execute the calculator calls.
    name="log data processing",  # By default, the function name is used as the tool name.
    description="A useful tool for processing log data",  # A description of the tool.
)
register_function(
    process_metric_data,
    caller=Observable_engineer_agent,  # The assistant agent can suggest calls to the calculator.
    executor=Operator,  # The user proxy agent can execute the calculator calls.
    name="metric data processing",  # By default, the function name is used as the tool name.
    description="A useful tool for processing metric data",  # A description of the tool.
)
register_function(
    process_trace_data,
    caller=Observable_engineer_agent,  # The assistant agent can suggest calls to the calculator.
    executor=Operator,  # The user proxy agent can execute the calculator calls.
    name="trace data processing",  # By default, the function name is used as the tool name.
    description="A useful tool for processing trace data",  # A description of the tool.
)
# 处理数据能力

# Group_chat = GroupChat(
#     messages=[],
#     agents=[RAG_user_proxy_agent, Operation_Engineer_Agent, Observable_engineer_agent, Operator,
#              NetWork_Expert_Agent, Architect_Expert_Agent, System_Expert_Agent],
#     send_introductions=True,
#     max_round=20,
# )
Group_chat = GroupChat(
    messages=[],
    agents=[User_proxy, Operation_Engineer_Agent, Observable_engineer_agent, Operator,
             NetWork_Expert_Agent, Architect_Expert_Agent, Resource_Expert_Agent],
    send_introductions=True,
    max_round=20,
)
Group_chat_manager = GroupChatManager(
    groupchat=Group_chat,
    llm_config=config_list,
)

# llm_lingua = LLMLingua()
# text_compressor = TextMessageCompressor(text_compressor=llm_lingua)
# context_handling = transform_messages.TransformMessages(transforms=[text_compressor])

# context_handling.add_to_agent(Operation_Engineer_Agent)
# context_handling.add_to_agent(Architect_Expert_Agent)
# context_handling.add_to_agent(Observable_engineer_agent)
# context_handling.add_to_agent(NetWork_Expert_Agent)
